name: publish
on: [push]
jobs:
publish-ptero-alpwine-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the ptero-alpwine Docker image
run: |
       docker build . --tag ghcr.io/ic3james/ptero-alpwine:latest
       docker run ghcr.io/ic3james/ptero-alpwine:latest
       docker push ghcr.io/ic3james/ptero-alpwine:latest
name: publish containers
on:
  push:
    branches: [ main ]
    paths:
    - pterodactyl/images/**
jobs:
  build:
    name: "${{ matrix.log }} build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tag:
         - ptero-alpwine
  steps:
  - uses: actions/checkout@v2
  - uses: docker/setup-buildx-actions@v1
   with:
    version: "v0.5.1"
    buildkit-flags: "--debug"
  - uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
          context: ./pterodactyl/images/${{ matrix.tag }}
          file: ./pterodactyl/images/${{ matrix.tag }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ic3james/${{ matrix.tag }}:latest  