name: publish
on: [push]
jobs:
publish-ptero-alpwine-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the ptero-alpwine Docker image
run: |
       docker build . --tag ghcr.io/ic3james/ptero-alpwine:latest
       docker run ghcr.io/ic3james/ptero-alpwine:latest
       docker push ghcr.io/ic3james/ptero-alpwine:latest